accountant: ClippingAccountant
clipping_prob: 0.01
input_files:
- EstablishmentLevelData/ri44_qbp_2016_1.csv
- EstablishmentLevelData/nj34_qbp_2016_1.csv
output:
  aggregate:
    folder: aggregated_data/budgets_reps
    suffix: agg
  measure_folder: measurements/budgets_reps
  postprocessed:
    folder: protected_data/budgets_reps
    suffix: protected
privacy_distances:
  m1emp: 0.5
  m2emp: 0.5
  m3emp: 0.5
  wage: 50.0
queries:
  groupby:
  - group: null
    mu:
      m1emp: 0.26013
      m2emp: 0.26013
      m3emp: 0.26013
      wage: 0.13007
    name: Sum Query
  - group:
    - cnty
    mu:
      m1emp: 0.7804
      m2emp: 0.7804
      m3emp: 0.7804
      wage: 0.1951
    name: By County
  - group:
    - naics5
    mu:
      m1emp: 0.7804
      m2emp: 0.7804
      m3emp: 0.7804
      wage: 0.1951
    name: By NAICS5
  - group:
    - cnty
    - naics5
    mu:
      m1emp: 0.91047
      m2emp: 0.91047
      m3emp: 0.91047
      wage: 0.1951
    name: By County/NAICS5
  identity:
    m1emp: 0.91047
    m2emp: 0.91047
    m3emp: 0.91047
    wage: 0.1951
reader: QCEWMicroDataReader
seed: 32
